version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: apocalipssi-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: apocalipssi

  ollama:
    image: ollama/ollama:latest
    container_name: apocalipssi-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    # Pas de command personnalisé, laissons Ollama démarrer normalement

  backend:
    build: ./backend
    container_name: apocalipssi-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - ollama
    environment:
      - CONNECTION_STRING=mongodb://mongodb:27017/apocalipssi
      - PORT=5000
      - NODE_ENV=development
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: apocalipssi-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
  ollama_data:
