version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: apocalipssi-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: apocalipssi

  backend:
    build: ./backend
    container_name: apocalipssi-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - CONNECTION_STRING=mongodb://mongodb:27017/apocalipssi
      - PORT=5000
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: apocalipssi-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
